---
- name: Converge
  become: true
  become_method: ansible.builtin.sudo
  hosts: all
  vars:
    vault_autoinit: true
  tasks:
  - name: Include andrelohmann.vault
    ansible.builtin.include_role:
      name: "andrelohmann.vault"
...
